### ISSUE TITLE
Upgrade to Firefox 57

### ISSUE THREAD

**Issue by chrishamm** [ashleybaldock/sixornot#13]
Thank you for this add-on, but it looks like it is no longer compatible with the latest Firefox version 57.
Is there any chance you could have a look at it?

**Comment by ashleybaldock** [comment]
Sadly Mozilla have made the decision to deprecate a large number of perfectly functional addons by moving to using the extension mechanism of the Chrome browser exclusively. They have not provided key functionality in the new API that SixOrNot requires to operate, and so attempting to update it would be pointless. I've tried to get this functionality added by appealing through their bug reporting process, to no avail.

I'd suggest using the IPvFoo addon which provides similar functionality (but is much uglier and doesn't do as much as SixOrNot). I've actually stopped using Firefox now due to this decision by Mozilla - I don't really believe in Firefox as a project anymore.

**Comment by chrishamm** [comment]
Hmm, that's a shame but thanks for the clarification. I hope Mozilla will eventually implement the missing functionality, though.

**Comment by ashleybaldock** [comment]
There is a WebExtension version of SixOrNot now :)

**Comment by chrishamm** [comment]
Thanks :)
